apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer  # This exposes the service with a public IP
  selector:
    app: frontend  # Match the pods labeled with "app: frontend"
  ports:
    - protocol: TCP
      port: 80         # The port exposed inside the cluster
      targetPort: 80   # The port on the container
